import React from "react";
import { Stethoscope, Sparkles, Leaf } from "lucide-react";
import { AnamTemplate } from "./types";

export const ACCEPTED_MIME = [
  "application/pdf",
  "application/msword",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "image/jpeg",
  "image/png",
  "image/webp",
  "image/gif",
];

export const TEMPLATE_OPTIONS: { value: AnamTemplate; label: string; desc: string; color: string; icon: React.ReactNode }[] = [
  { value: "reabilitacao", label: "Reabilitação", desc: "Fisioterapia, ortopedia, neurologia e pós-cirúrgico", color: "blue", icon: <Stethoscope className="w-4 h-4" /> },
  { value: "esteticaFacial", label: "Estética Facial", desc: "Pele, tratamentos faciais e procedimentos estéticos", color: "rose", icon: <Sparkles className="w-4 h-4" /> },
  { value: "esteticaCorporal", label: "Estética Corporal", desc: "Modelagem, celulite, gordura localizada e flacidez", color: "violet", icon: <Leaf className="w-4 h-4" /> },
];

export const emptyForm = {
  occupation: "",
  laterality: "",
  mainComplaint: "",
  diseaseHistory: "",
  cid10: "",
  painLocation: "",
  painAggravatingFactors: "",
  painRelievingFactors: "",
  functionalImpact: "",
  medicalHistory: "",
  previousTreatments: "",
  medications: "",
  allergies: "",
  familyHistory: "",
  tobaccoAlcohol: "",
  lifestyle: "",
  patientGoals: "",
  skinType: "",
  phototype: "",
  skinConditions: "",
  sunExposure: "",
  sunProtector: "",
  currentSkincareRoutine: "",
  previousAestheticTreatments: "",
  aestheticReactions: "",
  facialSurgeries: "",
  sensitizingMedications: "",
  aestheticHabits: "",
  sleepQuality: "",
  dietQuality: "",
  waterIntake: "",
  smoking: "",
  alcoholIntake: "",
  physicalActivity: "",
  bowelFunction: "",
  contraceptiveUse: "",
  aestheticMainComplaint: "",
  aestheticExpectations: "",
  currentWeight: "",
  height: "",
  targetWeight: "",
  bodyMainComplaint: "",
  bodyPainSymptoms: "",
  orthopedicProblems: "",
  vascularProblems: "",
  endocrineProblems: "",
  pacemakerMetal: "",
  aestheticGoal: "",
};
