export type ExamAttachment = {
  id: number;
  patientId: number;
  examTitle: string | null;
  originalFilename: string | null;
  contentType: string | null;
  fileSize: number | null;
  objectPath: string | null;
  description: string | null;
  resultText: string | null;
  uploadedAt: string;
};

export type AnamTemplate = "reabilitacao" | "esteticaFacial" | "esteticaCorporal";

export type AnamnesisForm = {
  occupation: string;
  laterality: string;
  mainComplaint: string;
  diseaseHistory: string;
  cid10: string;
  painLocation: string;
  painAggravatingFactors: string;
  painRelievingFactors: string;
  functionalImpact: string;
  medicalHistory: string;
  previousTreatments: string;
  medications: string;
  allergies: string;
  familyHistory: string;
  tobaccoAlcohol: string;
  lifestyle: string;
  patientGoals: string;
  skinType: string;
  phototype: string;
  skinConditions: string;
  sunExposure: string;
  sunProtector: string;
  currentSkincareRoutine: string;
  previousAestheticTreatments: string;
  aestheticReactions: string;
  facialSurgeries: string;
  sensitizingMedications: string;
  aestheticHabits: string;
  sleepQuality: string;
  dietQuality: string;
  waterIntake: string;
  smoking: string;
  alcoholIntake: string;
  physicalActivity: string;
  bowelFunction: string;
  contraceptiveUse: string;
  aestheticMainComplaint: string;
  aestheticExpectations: string;
  currentWeight: string;
  height: string;
  targetWeight: string;
  bodyMainComplaint: string;
  bodyPainSymptoms: string;
  orthopedicProblems: string;
  vascularProblems: string;
  endocrineProblems: string;
  pacemakerMetal: string;
  aestheticGoal: string;
};
