export const DEFAULT_PLANS = [
  {
    name: "essencial",
    displayName: "Essencial",
    description: "Para profissionais autônomos que estão começando",
    price: "149.00",
    maxProfessionals: 1,
    maxPatients: 150,
    maxSchedules: null,
    maxUsers: 3,
    trialDays: 14,
    features: [
      "1 profissional",
      "Até 150 pacientes",
      "Agenda completa",
      "Prontuários digitais",
      "Controle financeiro básico",
      "Suporte por e-mail",
    ],
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "profissional",
    displayName: "Profissional",
    description: "Para clínicas em crescimento com múltiplos profissionais",
    price: "299.00",
    maxProfessionals: 5,
    maxPatients: 600,
    maxSchedules: null,
    maxUsers: 10,
    trialDays: 30,
    features: [
      "Até 5 profissionais",
      "Até 600 pacientes",
      "Agenda completa",
      "Prontuários digitais",
      "Controle financeiro completo",
      "Relatórios avançados",
      "Assinaturas de pacientes",
      "Suporte prioritário",
    ],
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "premium",
    displayName: "Premium",
    description: "Para clínicas estabelecidas que precisam do máximo",
    price: "499.00",
    maxProfessionals: null,
    maxPatients: null,
    maxSchedules: null,
    maxUsers: null,
    trialDays: 30,
    features: [
      "Profissionais ilimitados",
      "Pacientes ilimitados",
      "Agenda completa",
      "Prontuários digitais",
      "Controle financeiro completo",
      "Relatórios avançados",
      "Assinaturas de pacientes",
      "API de integração",
      "White-label",
      "Suporte dedicado",
    ],
    isActive: true,
    sortOrder: 3,
  },
] as const;
