uploads = []
generated = []

[[outputs]]
id = "I51v9jRaVPL4tDUyopdug"
uri = "file://artifacts/fisiogest-pro-producao.zip"
type = "unspecified"
title = "FisioGest Pro - Pacote de Produção (Hostinger)"
