import { EvoTemplate } from "./types";

export const emptyEvoForm = {
  appointmentId: "" as string | number,
  description: "",
  patientResponse: "",
  clinicalNotes: "",
  complications: "",
  painScale: null as number | null,
  sessionDuration: "" as string | number,
  techniquesUsed: "",
  homeExercises: "",
  nextSessionGoals: "",
};

export const EVOLUTION_TEMPLATES: EvoTemplate[] = [
  {
    id: "ortopedica",
    name: "Fisioterapia Ortopédica",
    icon: "🦴",
    category: "Ortopedia",
    color: "bg-blue-50 border-blue-200 text-blue-700",
    description: "Realizada sessão de fisioterapia ortopédica com aplicação de recursos termoterápicos e cinesioterapia. Executados exercícios de fortalecimento muscular, alongamento e mobilização articular conforme plano terapêutico.",
    patientResponse: "Paciente apresentou boa tolerância aos exercícios propostos. Referiu melhora na amplitude de movimento e redução da sintomatologia dolorosa em relação à sessão anterior.",
    clinicalNotes: "Observada melhora progressiva da funcionalidade. Mantidas as condutas do plano terapêutico. Orientado sobre a importância da continuidade do tratamento e exercícios domiciliares.",
    complications: "",
    chips: {
      description: ["Eletroterapia (TENS/FES)", "Ultrassom terapêutico", "Crioterapia", "Termoterapia", "Exercícios de propriocepção", "Mobilização articular", "Massoterapia", "RPG"],
      patientResponse: ["Boa tolerância", "Refere melhora da dor", "Apresentou fadiga muscular", "Sem queixas adicionais", "Refere melhora funcional", "Dor durante o exercício"],
      clinicalNotes: ["Amplitude de movimento melhorada", "Força muscular progredindo", "Edema reduzido", "Marcha melhorada", "Orientações domiciliares fornecidas"],
      complications: ["Sem intercorrências", "Leve desconforto relatado", "Aumento temporário da dor", "Tontura durante exercício"],
    },
  },
  {
    id: "pilates",
    name: "Pilates Clínico",
    icon: "🧘",
    category: "Pilates",
    color: "bg-purple-50 border-purple-200 text-purple-700",
    description: "Sessão de Pilates clínico realizada no aparelho/solo. Trabalhados princípios de centralização, controle, precisão e respiração. Exercícios progressivos adaptados às necessidades e limitações do paciente.",
    patientResponse: "Paciente engajado e motivado durante a sessão. Demonstrou boa compreensão dos princípios do método e coordenação motora adequada na execução dos movimentos.",
    clinicalNotes: "Evolução positiva na estabilização do core e alinhamento postural. Exercícios com carga progressiva conforme tolerância. Coordenação respiratória em desenvolvimento.",
    complications: "",
    chips: {
      description: ["Exercícios no Reformer", "Exercícios no solo", "Cadillac", "Chair/Wunda", "Barrel/Tonnel", "Exercícios de respiração", "Ativação do core", "Fortalecimento global"],
      patientResponse: ["Ótima coordenação", "Dificuldade na respiração", "Boa estabilização", "Motivado e engajado", "Cansaço moderado", "Excelente execução"],
      clinicalNotes: ["Core estabilizado", "Postura melhorada", "Progressão de carga realizada", "Padrão respiratório melhorado", "Equilíbrio em desenvolvimento"],
      complications: ["Sem intercorrências", "Tensão lombar ao final", "Adaptação aos aparelhos"],
    },
  },
  {
    id: "neurologica",
    name: "Fisioterapia Neurológica",
    icon: "🧠",
    category: "Neurologia",
    color: "bg-indigo-50 border-indigo-200 text-indigo-700",
    description: "Sessão de fisioterapia neurológica com foco em reabilitação funcional. Aplicadas técnicas de facilitação neuromuscular proprioceptiva (FNP), estimulação sensório-motora e treino de atividades funcionais.",
    patientResponse: "Paciente colaborativo durante a sessão. Apresentou resposta adequada às estimulações propostas. Observada melhora na qualidade do movimento e controle motor.",
    clinicalNotes: "Evolução gradual do quadro motor e funcional. Mantida estimulação sensório-motora e treino de atividades de vida diária (AVDs). Família orientada sobre continuidade do tratamento.",
    complications: "",
    chips: {
      description: ["FNP (Kabat)", "Bobath / NDT", "Treino de marcha", "Equilíbrio e propriocepção", "Estimulação sensorial", "Treino de AVDs", "Eletroestimulação", "Treino cognitivo-motor"],
      patientResponse: ["Colaborativo", "Espasticidade aumentada", "Melhora no tônus", "Fadiga precoce", "Boa resposta às estimulações", "Agitação durante sessão"],
      clinicalNotes: ["Tônus muscular melhorado", "Controle motor progressivo", "Marcha com assistência", "Coordenação melhorada", "Família orientada"],
      complications: ["Sem intercorrências", "Espasmo durante exercício", "Cansaço excessivo", "Queda de pressão"],
    },
  },
  {
    id: "rpg",
    name: "RPG — Postural Global",
    icon: "🧍",
    category: "Postura",
    color: "bg-teal-50 border-teal-200 text-teal-700",
    description: "Sessão de Reeducação Postural Global (RPG) realizada. Trabalhadas posturas de fechamento/abertura em cadeia muscular posterior e anterior. Alongamentos globais e conscientização corporal.",
    patientResponse: "Paciente apresentou relaxamento muscular progressivo durante as posturas. Referiu sensação de alongamento e leveza após a sessão. Boa conscientização corporal.",
    clinicalNotes: "Melhora observada no alinhamento postural e flexibilidade das cadeias musculares. Paciente orientado sobre postura no cotidiano e ergonomia.",
    complications: "",
    chips: {
      description: ["Postura em pé fechamento", "Postura em pé abertura", "Postura sentado", "Postura deitada", "Cadeia posterior trabalhada", "Cadeia anterior trabalhada", "Trabalho respiratório"],
      patientResponse: ["Sensação de leveza", "Dor durante postura", "Boa conscientização", "Dificuldade de manter postura", "Relaxamento progressivo"],
      clinicalNotes: ["Lordose diminuída", "Cifose melhorada", "Escoliose monitorada", "Orientações ergonômicas fornecidas", "Flexibilidade aumentada"],
      complications: ["Sem intercorrências", "Desconforto lombar inicial", "Tensão cervical"],
    },
  },
  {
    id: "drenagem",
    name: "Drenagem Linfática",
    icon: "💆",
    category: "Estética / Linfático",
    color: "bg-pink-50 border-pink-200 text-pink-700",
    description: "Realizada sessão de drenagem linfática manual (DLM) com manobras de pressão leve e direcionamento do fluxo linfático. Técnica realizada de forma craniocaudal, respeitando os linfonodos regionais.",
    patientResponse: "Paciente bem tolerou os procedimentos, referindo relaxamento e sensação de leveza durante a sessão. Sem queixas de desconforto durante as manobras.",
    clinicalNotes: "Observada redução do edema na região tratada. Pele com melhor elasticidade e textura. Orientada sobre hidratação e hábitos de vida para potencializar os resultados.",
    complications: "",
    chips: {
      description: ["DLM clássico (Vodder)", "DLM pós-operatório", "DLM gestacional", "Região abdominal", "Membros inferiores", "Face e pescoço", "Manobras de chamada", "Manobras de reabsorção"],
      patientResponse: ["Sensação de leveza", "Relaxamento", "Sem desconforto", "Sonolência após sessão", "Redução da sensação de peso"],
      clinicalNotes: ["Edema reduzido", "Melhora da circulação", "Pele mais elástica", "Orientações nutricionais", "Hidratação recomendada"],
      complications: ["Sem intercorrências", "Vermelhidão transitória", "Sensibilidade aumentada"],
    },
  },
  {
    id: "pos-cirurgica",
    name: "Reabilitação Pós-Cirúrgica",
    icon: "🏥",
    category: "Pós-operatório",
    color: "bg-orange-50 border-orange-200 text-orange-700",
    description: "Sessão de fisioterapia pós-operatória realizada conforme protocolo estabelecido. Trabalhados mobilização precoce, controle do edema, cicatrização tecidual e recuperação funcional progressiva.",
    patientResponse: "Paciente colaborativo e motivado com a evolução do tratamento. Refere melhora em relação à sessão anterior. Tolerância ao exercício dentro do esperado para esta fase do protocolo.",
    clinicalNotes: "Evolução dentro do esperado para o período pós-operatório. Ferida cirúrgica em processo de cicatrização adequado. Amplitude de movimento progressiva conforme tolerância.",
    complications: "",
    chips: {
      description: ["Fase 1 — controle de edema", "Fase 2 — ganho de ADM", "Fase 3 — fortalecimento", "Fase 4 — retorno esportivo", "Crioterapia pós-exercício", "Mobilização precoce", "Descarga de peso progressiva"],
      patientResponse: ["Boa tolerância ao protocolo", "Dor controlada", "Melhora gradual", "Referiu cansaço", "Ansioso para progredir"],
      clinicalNotes: ["Cicatrização adequada", "Edema reduzido", "ADM aumentada", "Força muscular em progressão", "Gait sem compensações"],
      complications: ["Sem intercorrências", "Aumento do edema após exercício", "Dor além do esperado", "Vermelhidão na cicatriz"],
    },
  },
  {
    id: "eletroterapia",
    name: "Eletroterapia / TENS",
    icon: "⚡",
    category: "Recursos Físicos",
    color: "bg-yellow-50 border-yellow-200 text-yellow-700",
    description: "Aplicação de eletroterapia com corrente TENS (Estimulação Elétrica Nervosa Transcutânea) na região afetada. Parâmetros utilizados: modo convencional, frequência 80-100 Hz, duração de pulso 50-100µs, intensidade abaixo do limiar motor.",
    patientResponse: "Paciente referiu sensação de parestesia (formigamento) confortável durante a aplicação. Relatou alívio da dor ao término da sessão.",
    clinicalNotes: "Boa resposta analgésica ao TENS. Complementada com cinesioterapia e orientações ao paciente. Eletrodos posicionados adequadamente na região de dor referida.",
    complications: "",
    chips: {
      description: ["TENS modo convencional", "TENS acupuntura", "FES (estimulação muscular)", "Corrente interferencial", "Microcorrente (MENS)", "Ultrassom terapêutico", "Laser de baixa potência", "Ondas de choque"],
      patientResponse: ["Sensação de formigamento", "Alívio imediato da dor", "Contrações musculares toleradas", "Sem desconforto", "Leve ardência"],
      clinicalNotes: ["Analgesia obtida", "Eletrodos bem fixados", "Parâmetros ajustados", "Boa condutividade", "Sem reações cutâneas"],
      complications: ["Sem intercorrências", "Irritação cutânea leve", "Intolerância à intensidade", "Sensação desagradável"],
    },
  },
  {
    id: "respiratoria",
    name: "Fisioterapia Respiratória",
    icon: "🫁",
    category: "Cardiopulmonar",
    color: "bg-cyan-50 border-cyan-200 text-cyan-700",
    description: "Sessão de fisioterapia respiratória with aplicação de técnicas de higiene brônquica, reexpansão pulmonar e fortalecimento da musculatura respiratória. Realizada avaliação da ausculta pulmonar antes e após as técnicas.",
    patientResponse: "Paciente colaborativo durante as manobras. Apresentou melhora da saturação de O₂ após as técnicas. Referiu sensação de maior facilidade respiratória ao término da sessão.",
    clinicalNotes: "Ausculta pulmonar melhorada após as manobras. SpO₂ dentro dos parâmetros aceitáveis. Orientado sobre posicionamento e exercícios respiratórios domiciliares.",
    complications: "",
    chips: {
      description: ["Drenagem postural", "Vibrocompressão", "Huffing e tosse assistida", "Incentivador inspiratório", "IPPB", "Nebulização + fisioterapia", "Treino muscular inspiratório", "Respiração diafragmática"],
      patientResponse: ["Melhora da SpO₂", "Expectoração aumentada", "Dispneia reduzida", "Boa colaboração", "Cansaço após exercícios"],
      clinicalNotes: ["Ausculta melhorada", "Secreção mobilizada", "Expansibilidade aumentada", "FreqRES normalizada", "Orientações domiciliares"],
      complications: ["Sem intercorrências", "Broncoespasmo leve", "Queda transitória de SpO₂", "Tosse produtiva intensa"],
    },
  },
  {
    id: "sessao-inicial",
    name: "Primeira Sessão",
    icon: "🌟",
    category: "Especial",
    color: "bg-emerald-50 border-emerald-200 text-emerald-700",
    description: "Primeira sessão de fisioterapia realizada. Apresentação da clínica, explicação do plano terapêutico e objetivos do tratamento ao paciente. Iniciados exercícios introdutórios com carga leve para adaptação e avaliação da capacidade funcional.",
    patientResponse: "Paciente receptivo e motivado para iniciar o tratamento. Demonstrou interesse no plano terapêutico apresentado. Sem relatos de intolerância nas atividades iniciais.",
    clinicalNotes: "Sessão inicial de adaptação realizada com sucesso. Paciente orientado sobre frequência, duração e expectativas do tratamento. Condutas iniciais estabelecidas conforme avaliação funcional.",
    complications: "",
    chips: {
      description: ["Apresentação do plano terapêutico", "Avaliação funcional inicial", "Exercícios de adaptação", "Estabelecimento de metas", "Educação em dor", "Orientações gerais"],
      patientResponse: ["Motivado para o tratamento", "Receptivo às orientações", "Ansioso com as expectativas", "Dúvidas esclarecidas", "Comprometido com a frequência"],
      clinicalNotes: ["Metas terapêuticas definidas", "Plano de tratamento apresentado", "Capacidade funcional avaliada", "Exercícios domiciliares prescritos"],
      complications: ["Sem intercorrências", "Fadiga na avaliação inicial"],
    },
  },
  {
    id: "hidroterapia",
    name: "Hidroterapia",
    icon: "💧",
    category: "Aquático",
    color: "bg-sky-50 border-sky-200 text-sky-700",
    description: "Sessão de hidroterapia realizada em piscina terapêutica aquecida (32-34°C). Trabalhados exercícios de fortalecimento, alongamento e coordenação motora aproveitando as propriedades físicas da água.",
    patientResponse: "Paciente relatou bem-estar e alívio da dor durante a atividade aquática. Boa tolerância aos exercícios propostos no ambiente aquático. Motivado com a modalidade.",
    clinicalNotes: "Aproveitamento adequado das propriedades físicas da água (flutuação, resistência, hidrodinâmica). Exercícios progressivos conforme adaptação e tolerância do paciente.",
    complications: "",
    chips: {
      description: ["Exercícios de flutuação", "Caminhada aquática", "Fortalecimento resistido", "Propriocepção aquática", "Relaxamento Watsu", "Bad Ragaz rings", "Exercícios de equilíbrio"],
      patientResponse: ["Alívio da dor na água", "Boa flutuação", "Motivado", "Cansaço ao término", "Sensação de bem-estar"],
      clinicalNotes: ["Temperatura da água adequada", "Progressão de exercícios realizada", "Orientações de segurança", "Hidratação recomendada"],
      complications: ["Sem intercorrências", "Tonturas após saída da água", "Arranhão de borda", "Intolerância à temperatura"],
    },
  },
  {
    id: "pilates-grupo",
    name: "Pilates em Grupo",
    icon: "👥",
    category: "Pilates",
    color: "bg-violet-50 border-violet-200 text-violet-700",
    description: "Sessão de Pilates em grupo realizada com turma reduzida. Trabalhados princípios do método com adaptações para o formato coletivo: centralização, controle, precisão e respiração. Exercícios de solo e/ou pequenos acessórios.",
    patientResponse: "Grupo demonstrou boa participação e engajamento durante a sessão. Pacientes motivados com a dinâmica em grupo. Boa interação e execução dos movimentos propostos.",
    clinicalNotes: "Turma com progresso homogêneo. Exercícios individualizados quando necessário para adaptação às limitações de cada participante. Ambiente favorável à prática coletiva.",
    complications: "",
    chips: {
      description: ["Exercícios de solo", "Acessórios (bola, faixa, anel)", "Sequência standing", "Aquecimento em grupo", "Exercícios de respiração coletiva", "Alongamento final em grupo", "Ativação do core em grupo"],
      patientResponse: ["Boa integração ao grupo", "Motivados pela dinâmica coletiva", "Solicitaram progressão", "Cansaço moderado", "Excelente colaboração", "Dificuldade em acompanhar ritmo"],
      clinicalNotes: ["Turma nivelada", "Adaptação individual realizada", "Progressão coletiva realizada", "Orientações individualizadas", "Nível intermediário atingido"],
      complications: ["Sem intercorrências", "Participante com limitação específica", "Cansaço excessivo de um participante"],
    },
  },
  {
    id: "massoterapia",
    name: "Massagem / Massoterapia",
    icon: "🤲",
    category: "Estética / Relaxamento",
    color: "bg-rose-50 border-rose-200 text-rose-700",
    description: "Sessão de massoterapia/massagem terapêutica realizada com manobras de deslizamento, amassamento, fricção e percussão. Técnica adaptada às necessidades e preferências do paciente, com foco nas regiões de maior tensão muscular.",
    patientResponse: "Paciente relatou relaxamento progressivo durante a sessão. Referiu alívio das tensões musculares e sensação de bem-estar ao término. Boa tolerância à pressão aplicada.",
    clinicalNotes: "Identificadas regiões de maior tensão muscular e pontos-gatilho. Manobras direcionadas às áreas de maior contração. Paciente orientado sobre hidratação pós-sessão.",
    complications: "",
    chips: {
      description: ["Massagem relaxante", "Massagem desportiva", "Massagem terapêutico profunda", "Liberação miofascial", "Pontos-gatilho (trigger points)", "Região cervical e ombros", "Região lombar", "Membros inferiores", "Corpo inteiro"],
      patientResponse: ["Relaxamento profundo", "Alívio imediato das tensões", "Sonolência após sessão", "Dor à pressão nos pontos-gatilho", "Sensação de leveza muscular"],
      clinicalNotes: ["Tensão muscular reduzida", "Pontos-gatilho tratados", "Circulação local melhorada", "Orientação de hidratação", "Presença de nódulos miofasciais"],
      complications: ["Sem intercorrências", "Sensibilidade elevada na região", "Vermelhidão local transitória", "Hematoma superficial"],
    },
  },
  {
    id: "radiofrequencia",
    name: "Radiofrequência",
    icon: "📡",
    category: "Estética",
    color: "bg-amber-50 border-amber-200 text-amber-700",
    description: "Sessão de radiofrequência realizada para remodelamento tissular e estimulação do colágeno. Aplicação com cabeçote deslizante na região tratada, mantendo temperatura terapêutica entre 40-42°C durante o tempo de exposição.",
    patientResponse: "Paciente relatou sensação de calor confortável durante a aplicação. Boa tolerância ao procedimento. Sem queixas de desconforto excessivo durante a sessão.",
    clinicalNotes: "Temperatura monitorada durante toda a aplicação. Pele hidratada e com melhora de elasticidade observada. Orientada sobre cuidados pós-sessão: hidratação e fotoproteção.",
    complications: "",
    chips: {
      description: ["Radiofrequência facial", "Radiofrequência corporal", "Radiofrequência abdominal", "Radiofrequência em flacidez", "Radiofrequência fracionada", "Região de papada", "Região de coxa e glúteo", "Região de braços"],
      patientResponse: ["Calor agradável", "Boa tolerância", "Sensação de firmeza imediata", "Leve vermelhidão transitória", "Sem desconforto"],
      clinicalNotes: ["Temperatura monitorada (40-42°C)", "Pele com maior elasticidade", "Colágeno estimulado", "Fotoproteção orientada", "Hidratação recomendada"],
      complications: ["Sem intercorrências", "Vermelhidão persistente", "Queimação leve", "Bolha ou eritema intenso"],
    },
  },
  {
    id: "ultrassom",
    name: "Ultrassom Terapêutico",
    icon: "🔊",
    category: "Recursos Físicos",
    color: "bg-slate-50 border-slate-300 text-slate-700",
    description: "Aplicação de ultrassom terapêutico na região afetada. Modo contínuo para efeito térmico (aquecimento profundo) ou pulsado para efeito mecânico (anti-inflamatório). Frequência e intensidade ajustadas conforme a patologia e profundidade do tecido-alvo.",
    patientResponse: "Paciente relatou sensação de calor leve e profundo durante a aplicação (modo contínuo) / sem sensação significativa (modo pulsado). Boa tolerância ao procedimento.",
    clinicalNotes: "Gel condutor utilizado em quantidade adequada. Cabeçote mantido em movimento constante durante a aplicação. Parâmetros ajustados conforme fase do processo inflamatório.",
    complications: "",
    chips: {
      description: ["Modo contínuo (térmico)", "Modo pulsado (anti-inflamatório)", "Frequência 1 MHz (tecidos profundos)", "Frequência 3 MHz (tecidos superficiais)", "Articulação do ombro", "Região lombossacral", "Joelho", "Tendões e ligamentos"],
      patientResponse: ["Calor leve e agradável", "Sem sensação térmica (pulsado)", "Boa tolerância", "Alívio após aplicação"],
      clinicalNotes: ["Gel condutor adequado", "Cabeçote em movimento constante", "Parâmetros: frequência/intensidade/tempo registrados", "Redução do processo inflamatório esperada"],
      complications: ["Sem intercorrências", "Queimação local", "Dor ao toque na região", "Dermatite de contato com gel"],
    },
  },
  {
    id: "acupuntura",
    name: "Acupuntura",
    icon: "🪡",
    category: "Medicina Tradicional Chinesa",
    color: "bg-emerald-50 border-emerald-300 text-emerald-800",
    description: "Sessão de acupuntura realizada com inserção de agulhas estéreis em pontos específicos dos meridianos. Foco no equilíbrio energético, alívio da dor e modulação do sistema nervoso.",
    patientResponse: "Paciente relatou sensação de 'De Qi' (distensão/peso leve) durante a inserção. Referiu relaxamento profundo durante o período de permanência das agulhas. Boa aceitação da técnica.",
    clinicalNotes: "Pontos selecionados conforme avaliação energética e queixa principal. Agulhas mantidas por 20-30 minutos. Nenhuma intercorrência durante a inserção ou retirada.",
    complications: "",
    chips: {
      description: ["Pontos de analgesia", "Pontos de relaxamento", "Acupuntura sistêmica", "Auriculoterapia", "Eletroacupuntura", "Ventosaterapia associada", "Moxabustão", "Gua Sha"],
      patientResponse: ["Sensação de relaxamento", "Redução da ansiedade", "Alívio da dor local", "Sensação de energia fluindo", "Leve sonolência"],
      clinicalNotes: ["Agulhas estéreis descartadas", "Pontos: IG4, F3, E36, VG20, VB34", "Tempo de permanência: 20 min", "Resposta vasovagal negativa"],
      complications: ["Sem intercorrências", "Pequeno hematoma pontual", "Sensação de desmaio (vasovagal)", "Dor na inserção"],
    },
  },
];
