// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/brand-book/Page.tsx": () => import("../components/mockups/brand-book/Page.tsx"),
  "./components/mockups/pitch-deck/Page.tsx": () => import("../components/mockups/pitch-deck/Page.tsx"),
  "./components/mockups/tech-docs/Page.tsx": () => import("../components/mockups/tech-docs/Page.tsx")
};
