// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pitch-deck/Page.tsx": () => import("../components/mockups/pitch-deck/Page.tsx"),
  "./components/mockups/tech-docs/Page.tsx": () => import("../components/mockups/tech-docs/Page.tsx"),
  "./components/mockups/brand-book/ColorSystem.tsx": () => import("../components/mockups/brand-book/ColorSystem.tsx"),
  "./components/mockups/brand-book/IconSystem.tsx": () => import("../components/mockups/brand-book/IconSystem.tsx"),
  "./components/mockups/brand-book/LogoSystem.tsx": () => import("../components/mockups/brand-book/LogoSystem.tsx"),
  "./components/mockups/brand-book/Page.tsx": () => import("../components/mockups/brand-book/Page.tsx"),
  "./components/mockups/loaders/EsteticaLoader.tsx": () => import("../components/mockups/loaders/EsteticaLoader.tsx"),
  "./components/mockups/loaders/FisioterapiaLoader.tsx": () => import("../components/mockups/loaders/FisioterapiaLoader.tsx"),
  "./components/mockups/loaders/IconBone.tsx": () => import("../components/mockups/loaders/IconBone.tsx"),
  "./components/mockups/loaders/IconHand.tsx": () => import("../components/mockups/loaders/IconHand.tsx"),
  "./components/mockups/loaders/IconHeartPulse.tsx": () => import("../components/mockups/loaders/IconHeartPulse.tsx"),
  "./components/mockups/loaders/IconStethoscope.tsx": () => import("../components/mockups/loaders/IconStethoscope.tsx"),
  "./components/mockups/loaders/PilatesLoader.tsx": () => import("../components/mockups/loaders/PilatesLoader.tsx")
};
